### ISSUE TITLE
Int.Hash_set.mem

### ISSUE THREAD

**Issue by rgrig** [janestreet/core#103]
Maybe I'm misreading the docs, but isn't there supposed to be an `Int.Hash_set.mem`? With **v0.10.0** I get "unbound value".
https://asciinema.org/a/yICqwovJ6Q07nrJ8xsWKG4jZH

**Comment by hhugo** [comment]
Use should use `Hash_set.mem` directly.

**Comment by rgrig** [comment]
thanks!
