### ISSUE TITLE
Add function to copy files

### ISSUE THREAD

**Issue by XVilka** [janestreet/core#107]
Because just "Unix.rename" is not enough for all cases.

**Comment by yminsky** [comment]
This is a bit of a complicated thing to implement, with lots of choices to be made on a platform by platform basis. You can use Core_extended.Shell which has a cp function, backed by invoking the cp program.

**Comment by XVilka** [comment]
Apparently it is not a complicated thing to implement for other languages like [Rust](https://doc.rust-lang.org/1.4.0/std/fs/fn.copy.html), [C++](http://en.cppreference.com/w/cpp/filesystem/copy) or [Elixir](https://hexdocs.pm/elixir/File.html)

**Comment by yminsky** [comment]
No need to be snide.

In any case, I did point to to an implementation in core extended (in OCaml no less!).
