### ISSUE TITLE
Core Dump in Time Functions after Clock Reset

### ISSUE THREAD

**Issue by lindig** [janestreet/core#119]
I'd like to apologize in advance for a vague error report without a tight reproduction. We are using Core v0.11.3 and Async in an application. During tests we reset the clock and this leads to core dumps. Now it could be argued that the clock should not be reset but it might even happen from ntpd correcting the time. I suspect this is caused by the calculations around time stamps:

https://github.com/janestreet/core/blob/master/src/time_stamp_counter.ml#L1-L68

Maybe there is away to make this more robust? I was not able to quickly reproduce this in a small standalone binary. We would be happy to share the binary where this happens. At this point, I just would like to start the discussion.

```
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (((pid 1042) (thread_id 0)) "2010-01-01 01:00:02.540395647Z"
Jan  1 01:00:02 localhost xapi-storage-script[1042]: "unhandled exception in Async scheduler"
Jan  1 01:00:02 localhost xapi-storage-script[1042]: ("bug in async scheduler"
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (((Invalid_argument
Jan  1 01:00:02 localhost xapi-storage-script[1042]: "Float.iround_nearest_exn: argument (-nan) is too small or NaN")
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (calibrator
Jan  1 01:00:02 localhost xapi-storage-script[1042]: ((time 1262307602.5166039) (tsc 8604177243276) (sec_per_cycle -NAN)
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (monotonic_time 1535579583.7254214) (monotonic_sec_per_cycle NAN)
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (monotonic_until_tsc 0) (ewma_time_tsc INF) (ewma_tsc_square -NAN)
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (ewma_time INF) (ewma_tsc -NAN) (time_nanos 1262307602516603904)
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (nanos_per_cycle -NAN) (monotonic_time_nanos 1535579583725421312)
Jan  1 01:00:02 localhost xapi-storage-script[1042]: (monotonic_nanos_per_cycle NAN))))
```

**Comment by yminsky** [comment]
Interesting. We'll take a look.

**Comment by lindig** [comment]
I managed to reproduce the issue with this code:
```
open Core
module TSC = Time_stamp_counter

let main () =
  let _c = TSC.Calibrator.create () in
  let () = TSC.Calibrator.calibrate () in
  let start = TSC.now () in
  Unix.sleep 5 ;
  TSC.Calibrator.calibrate () ;
  let ns =
    TSC.diff (TSC.now ()) start
    |> TSC.Span.to_ns |> Int63.to_int
    |> function Some x -> x | None -> 0
  in
  Printf.printf "span = %d ns\n" ns

let () = main ()
```

The code pauses for 5 seconds where I reset the clock:

```
[root@lcy2-dt110 tmp]# ./main.exe & sleep 2 && date +%Y%m%d -s "20120418"; fg
[1] 19334
20120418
./main.exe
Uncaught exception:
  
  (Invalid_argument
   "Float.iround_nearest_exn: argument (-nan) is too small or NaN")

Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "src/float.ml" (inlined), line 441, characters 4-89
Called from file "src/float.ml", line 601, characters 60-82
Called from file "main.ml", line 11, characters 4-53
Called from file "main.ml", line 17, characters 9-16
```

It is important to set back the clock more than just a couple of minutes. In the original code we saw a core dump where here we just see an exception.

**Comment by lindig** [comment]
My hunch is that Core implements its own time function for enhanced precision and this is also used by the Async scheduler. Unfortunately, it seems it is not robust against large time changes.

**Comment by aalekseyev** [comment]
Thank you. I think this is clearly a bug.
In this case I suspect the value of `alpha` in `time_stamp_counter.ml` becomes minus infinity which leads to infinities propagated everywhere and breaks things. (I suspect any large negative value is problematic, even though it may not lead to a crash)

If you want a fix you could try right now, I would suggest changing `alpha_for_interval` in `time_stamp_counter.ml` to this:

    let alpha_for_interval time_diff =
      Float.max 0.0 (1. -. exp (-0.5 *. time_diff))
    ;;

Otherwise, stay tuned for an eventual fix.

**Comment by aalekseyev** [comment]
This was fixed at some point by making the above change.
