### ISSUE TITLE
wait_nohang doc is misleading

### ISSUE THREAD

**Issue by sepeth** [janestreet/core#120]
Hi,

I think wait_nohang doc is misleading. It says `"The nohang variants return None immediately if no such process exists."` but that's not the case, I get an exception in this case (this happened while I tried to wait on an already exited child):

```
(Unix.Unix_error "No child processes" waitpid
  "((mode (WNOHANG)) (pid 89819))")
Thread 1 killed on uncaught exception Unix.Unix_error(5, "waitpid", "((mode (WNOHANG)) (pid 89819))")
```

Man pages for WNOHANG says something else, waitpid(2) on Linux:

```
WNOHANG return immediately if no child has exited.
```

On macOS:

```
The WNOHANG option is used to indicate that the call should not
block if there are no processes that wish to report status.
```

Thanks

**Comment by diml** [comment]
That's odd, I don't see anything special when reading the code of this function. What does the vanilla `Unix.waitpid [WNOHANG] pid` reports in this case?

**Comment by sepeth** [comment]
Oh sorry if my explanation was also misleading :) There is nothing wrong in
the code, and I see the code is doing nothing different, just the doc
seemed wrong.

**Comment by diml** [comment]
Ah indeed. I just saw the paragraph documenting this function and it definitely looks wrong.

**Comment by diml** [comment]
I suggest:

```
The [nohang] variants return [None] immediately if none of the desired processes has
exited yet.
```

does that look clear to you?

**Comment by sepeth** [comment]
That looks much better, thanks :)

**Comment by diml** [comment]
No problem. I pushed the change internally, it will surface up on github in a few days.
