### ISSUE TITLE
Unbound module Core.Lock_file

### ISSUE THREAD

**Issue by toolslive** [janestreet/core#134]
After installing `core.v0.12.3` via opam on `4.08.0` the module `Core.Lock_file` has gone awol.
I can see that the package library contains a file `lock_file_blocking.mli` 
but the module `Lock_file_blocking` doesn't seem to be available.

**Comment by bcc32** [comment]
You can access the `Lock_file_blocking` library using the ocamlfind name `core.lock_file_blocking` in, say, a dune file.  Please refer the `public_name` stanza in the dune file for the name you need to use for any of the libraries which have been split out.
