### ISSUE TITLE
Feature request + patch: Core.Filename.relpath to compute a path relative to another

### ISSUE THREAD

**Issue by cpitclaudel** [janestreet/core#136]
Hi there,

Thanks for the hard work on `core`.

I couldn't find a function in `Core.Filename` to compute a relative version of a path given an absolute path and a root.  This is [`os.path.relpath`](https://docs.python.org/3.8/library/os.path.html#os.path.relpath) in Python, and the implementation [is simple](https://github.com/python/cpython/blob/2c4c02f8a876fcf084575dcaf857a0236c81261a/Lib/posixpath.py#L449).

In OCaml it would look like this:

```ocaml
open Core

let abspath (path: string) =
  if Filename.is_relative path then
    Filename.concat (Sys.getcwd ()) path
  else path

let rec skip_common_prefix l1 l2 =
  match l1, l2 with
  | h1 :: t1, h2 :: t2 when h1 = h2 -> skip_common_prefix t1 t2
  | _ -> l1, l2

let relpath (path: string) (start: string) =
  let open Filename in
  let pparts = parts (abspath path) in
  let sparts = parts (abspath start) in
  let ponly, sonly = skip_common_prefix pparts sparts in
  let go_up = List.map ~f:(fun _ -> parent_dir_name) sonly in
  match go_up @ ponly with
  | [] -> current_dir_name
  | relpath -> of_parts relpath
```

And the test cases:

````
let _ =
  assert (relpath "/a/b/c" "/" = "a/b/c");
  assert (relpath "/a/b/c" "/a" = "b/c");
  assert (relpath "/a/b/c" "/a/" = "b/c");
  assert (relpath "/a/b/c" "/a/b" = "c");
  assert (relpath "/a/b/c" "/a/b/" = "c");
  assert (relpath "/a/b/c" "/a/b/d" = "../c");
  assert (relpath "/a/b/c" "/a/b/d/" = "../c");
  assert (relpath "/a/b/c" "/a/d" = "../b/c");
  assert (relpath "/a/b/c" "/a/d/" = "../b/c");
  assert (relpath "/a/b/c" "/a/d/e" = "../../b/c");
  assert (relpath "/a/b/c" "/a/d/e/" = "../../b/c");
  assert (relpath "/a/b/c" "/a/d/e/" = "../../b/c");
  assert (relpath "/a/b/c/" "/" = "a/b/c");
  assert (relpath "/a/b/c/" "/a" = "b/c");
  assert (relpath "/a/b/c/" "/a/" = "b/c");
  assert (relpath "/a/b/c/" "/a/b" = "c");
  assert (relpath "/a/b/c/" "/a/b/" = "c");
  assert (relpath "/a/b/c/" "/a/b/d" = "../c");
  assert (relpath "/a/b/c/" "/a/b/d/" = "../c");
  assert (relpath "/a/b/c/" "/a/d" = "../b/c");
  assert (relpath "/a/b/c/" "/a/d/" = "../b/c");
  assert (relpath "/a/b/c/" "/a/d/e" = "../../b/c");
  assert (relpath "/a/b/c/" "/a/d/e/" = "../../b/c");
  assert (relpath "/a/b/c/" "/a/d/e/" = "../../b/c");
  assert (relpath "./a/b/c" "./" = "a/b/c");
  assert (relpath "./a/b/c" "./a" = "b/c");
  assert (relpath "./a/b/c" "./a/" = "b/c");
  assert (relpath "./a/b/c" "./a/b" = "c");
  assert (relpath "./a/b/c" "./a/b/" = "c");
  assert (relpath "./a/b/c" "./a/b/d" = "../c");
  assert (relpath "./a/b/c" "./a/b/d/" = "../c");
  assert (relpath "./a/b/c" "./a/d" = "../b/c");
  assert (relpath "./a/b/c" "./a/d/" = "../b/c");
  assert (relpath "./a/b/c" "./a/d/e" = "../../b/c");
  assert (relpath "./a/b/c" "./a/d/e/" = "../../b/c");
  assert (relpath "./a/b/c" "./a/d/e/" = "../../b/c")
```

**Comment by Ngoguey42** [comment]
👍

**Comment by aalekseyev** [comment]
[Added](https://github.com/janestreet/core_kernel/commit/ef1d7f6a71e43f6465ccdf9285f8a2adf6a7cbab#diff-a4f597e3c32afe136184f9ab86c88ca857fb853b5ab27113ebc5640786534ee8) `Core_kernel.Filename.of_absolute_exn` for converting absolute paths into relative ones.

Looks like it's not the same as what you proposed, but it's intended to serve a similar purpose.
I'm closing the issue assuming that is sufficient. Please let us know if that is not so.

**Comment by cpitclaudel** [comment]
> Looks like it's not the same as what you proposed

… really? It's the exact same, down to the variable names and the tests — please acknowledge the source of the code next time :)

**Comment by TyOverby** [comment]
@cpitclaudel: The behavior of the two functions is different, I think that's all @aalekseyev is trying to say

**Comment by aalekseyev** [comment]
@cpitclaudel, sorry, I was not involved in making this change, so I did not know to what extent your code was used.
All I meant to say that the behavior seems to be slightly different. (your code seems to be normalizing relative paths, whereas the code in core fails on them)

Thanks a lot for your contribution!

**Comment by aalekseyev** [comment]
I guess I forgot to close this issue before. Closing it now.
