### ISSUE TITLE
Error when using the List.Assoc module

### ISSUE THREAD

**Issue by silveradd001** [janestreet/core#139]
Hi there, I am trying to use the List.Assoc module to find an item in an assocciation like this one:

let assoc = [("one", 1); ("two", 2); ("three", 3)]

but when I try the pattern matching:

 match List.Assoc.find assoc "Two" with
      |None -> 0
      |Some x -> x

I get the following error:

Error: This pattern matches values of type 'a option
       but a pattern was expected which matches values of type
         equal:(string -> string -> bool) -> int option

Any hints on what I may be doing wrong?

Thanks,

Alex.

**Comment by dwang20151005** [comment]
You didn't pass the [~equal] argument.

Do you know of [discuss.ocaml.org]?  The "learning" category is very
friendly to basic questions such as this:

https://discuss.ocaml.org/c/learning/7

Welcome to OCaml.  Good luck, have fun.

Wang

**Comment by silveradd001** [comment]
Thank you Wang, I suppose I didn't really understand what information to pass down to the [~equal] argument when reading the function signature:

find : ('a, 'b) t -> ?equal:('a -> 'a -> bool) -> 'a -> 'b option

I thought '?' meant 'equal' was an optional argument.

Thanks for the link to the OCaml discussion board, hope I'll find the solution ^^

Rgds,

Alex.

**Comment by bcc32** [comment]
I think you are looking at an outdated version of the documentation.  The `equal` argument has been required for some time, see [here](https://ocaml.janestreet.com/ocaml-core/latest/doc/base/Base/List/Assoc/index.html) for example.

**Comment by silveradd001** [comment]
I see your point, google points to an old documentation I suppose.

Thank you for the support, really appreciated, and the OCaml discission forum has been of help as well.

Thanks again.
