### ISSUE TITLE
Failed to compile core v0.16 on windows

### ISSUE THREAD

**Issue by Chimrod** [janestreet/core#165]
Hello,

I’m using OCaml with mingw, and I can’t install core.

```bash
core.v0.16.0 dune build
File "core/src/dune", line 1, characters 0-83:
1 | (rule (targets config.h) (deps)
2 |  (action (bash "cp %{lib:jst-config:config.h} .")))
cp: impossible d'évaluer 'D:home.opam4.14.0+flambda+mingw64libjst-configconfig.h': No such file or directory
```

The path to the file is not properly evaluated because the system use windows path separator, and it is not correctly interpreted in the compilation.

The error is located in dune which use bash explicitly : https://github.com/janestreet/core/blob/master/core/src/dune#L2

**Comment by dkalinichenko-js** [comment]
Hi, this will be resolved by the release v0.16.2, which should make its way into opam in a few days.
