### ISSUE TITLE
Unable to install on mips64el architecture

### ISSUE THREAD

**Issue by WardBrian** [janestreet/core#167]
Core v0.15.0 and v0.16.0 both fail to opam-install with only
`Sorry, no solution found: there seems to be a problem with your request.`

Core_kernel was previously installable on this arch (v0.14.1)

**Comment by dkalinichenko-js** [comment]
Hi! This looks like some issue with the opam dependency solver, could you post a more detailed issue at https://github.com/ocaml/opam/issues? Thanks.
