### ISSUE TITLE
Uses of int{32,64} should be replaced with int{32,64}_t

### ISSUE THREAD

**Issue by jonludlam** [janestreet/core#49]
Due to this issue that's been fixed in trunk OCaml:

http://caml.inria.fr/mantis/view.php?id=6517

This affects people using the latest 4.02.1 compiler in Fedora, too, as the patch has been backported (see Richard Jones's last comment).

Changes are required in lib/backtrace_stubs.c and lib/ocaml_utils.h

**Comment by bmillwood** [comment]
I did a few greps, and I think we're using int32_t and int64_t as appropriate now. Re-open if you find any instances I've missed.
