### ISSUE TITLE
Time.of_string should return a Result.t

### ISSUE THREAD

**Issue by antoine1fr** [janestreet/core#54]
Time.of_string currently raises an exception when it fails to parse the given string.

According to Core's coding style, there should be two versions of this function:

```ocaml
val of_string : string -> (t, string) Result.t (* or t Option.t *)
val of_string_exn : string -> t
```

**Comment by yminsky** [comment]
The of_string functions are all like this, and have been for a long time.
We decided that it wasn't worth the large amount of churn to fix, but it
makes us sad too...

**Comment by antoine1fr** [comment]
Fair enough, thanks for the answer anyway ! :)
