### ISSUE TITLE
Syntax extensions in core's dependencies

### ISSUE THREAD

**Issue by Drup** [janestreet/core#55]
pa_pipebang is a dependency of core while it's only a syntax extension.

There was another one, but I can't find it now. Will post again if I do.

**Comment by yminsky** [comment]
Could you please be more precise?  pa_pipebang is a dependency of Core in the sense that Core uses pa_pipebang.  On IRC, you were claiming something weirder, that somehow if you use Core and camlp4, you're then forced by ocamlfind to use pa_pipebang.  I don't understand the details, so it would be helpful if you could explain the precise misbehavior and how to replicate it.

**Comment by Drup** [comment]
Yes, ocamlfind will load pa_pipebang because of this line : https://github.com/janestreet/core/blob/master/_oasis#L290

**Comment by yminsky** [comment]
Would you mind providing a command-line invocation that demonstrates the problem?  Thanks.

**Comment by diml** [comment]
I see the problem. Usually our syntax extensions are named `package.syntax`. Often the syntax extension has a runtime part so we add `package` in the META dependencies and `package` & `package.syntax`  in the build dependencies. pa_pipebang doesn't follow this rules and defines the syntax extension under the package `pa_pipebang`. And it was wrongly added to the META dependencies of core.
