### ISSUE TITLE
corebuild disappeared

### ISSUE THREAD

**Issue by roberthoeppner** [janestreet/core#62]

**Comment by avsm** [comment]
Why was this closed? Corebuild does indeed seem to have disappeared in recent releases... /cc @yminsky @diml

**Comment by roberthoeppner** [comment]
I deleted it because I thought I was just unable to find it and didn’t want to bother others with that. 

Sorry,

Robert

**Comment by avsm** [comment]
Nope, you were spot on! :)  Thanks for creating the report...

**Comment by diml** [comment]
I have core 112.35.00 installed and corebuild is properly installed. What version of core are you using?

**Comment by avsm** [comment]
112.35.01

**Comment by avsm** [comment]
it would be good to fold it in upstream and not in `files/` in opam repository if possible.

**Comment by diml** [comment]
@avsm, OK I created a pull request for core 112.35.01 and imported `core.install` to the core repository.

**Comment by avsm** [comment]
and merged, thanks!
