### ISSUE TITLE
Command auto-completion script fails on Mac

### ISSUE THREAD

**Issue by agarwal** [janestreet/core#63]
Previous versions of Core used to generate

```
COMPREPLY=($("${COMP_WORDS[@]}"))
```

in the autocompletion script from Command. This worked fine on Mac.

Now, this is done:

```
if type readarray > /dev/null
then readarray -t COMPREPLY < <("${COMP_WORDS[@]}")
else IFS="
" read -d "" -A COMPREPLY < <("${COMP_WORDS[@]}")
```

Unfortunately there is no `readarray` on Mac. Thus we fall over to the `else` case, which just doesn't parse in bash.

**Comment by dwang20151005** [comment]
readarray was introduced in bash-4.0 and it [looks like](http://apple.stackexchange.com/questions/100915/what-version-of-bash-comes-with-osx-10-9-mavericks) Mac OS X ships with bash-3.2.

Could you confirm that you are using vanilla bash and tell me the version number?

**Comment by agarwal** [comment]
```
$ type bash
bash is /bin/bash

$ bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by shayne-fletcher** [comment]
Bash 4.0 is now available for MacOS using brew and the autocompletion scripts demonstrated to work.
