### ISSUE TITLE
Error when requiring core or async at toplevel

### ISSUE THREAD

**Issue by beneyal** [janestreet/core#65]
When I'm running either ocaml or utop with the .ocamlinit shown in the [Installation hints](http://janestreet.github.io/installation.html), I'm getting the following error:

```
Exception:
Zone.Invalid_file_format "/etc/localtime - version (3) is invalid".
File ".ocamlinit", line 1:
Error: Reference to undefined global `Core'
```

My .ocamlinit file:

``` ocaml
(* Added by OPAM. *)
let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;

(* Added by Me *)
#use "topfind"
#thread
#require "dynlink"
#camlp4o
#require "bin_prot.syntax"
#require "sexplib.syntax"
#require "variantslib.syntax"
#require "fieldslib.syntax"
#require "comparelib.syntax"
#require "core"
#require "async"
#require "core_extended"
#require "core.top"
open Core.Std
```

I do not get the error if I remove lines requiring "core", "async", "core_extended", "core.top", and the open, of course.
I am running OCaml 4.02.3 (Core is at version 113.00.00) on an Arch Linux machine.

EDIT:
I'm pretty sure this is what's giving me the error:

``` ocaml
let read_header ic =
  let buf = String.create 4 in
  really_input ic buf 0 4;
  if buf <> "TZif" then
    raise (Invalid_file_format "magic characters TZif not present");
  let version =
    match input_char ic with
      | '\000' -> `V1
      | '2' -> `V2
      | bad_version ->
        raise (Invalid_file_format (sprintf "version (%c) is invalid" bad_version))
```

I checked my /etc/localtime, and indeed, the header is TZif3. I'm not sure where to continue from here.

**Comment by bmillwood** [comment]
Looks like there's a newer timezone file format we just didn't know about. I'll see if I can find out how much work it would be to write the code for it.

There's some notes on the differences in [eggert/tz](https://github.com/eggert/tz/blob/198708147f6b1fd81d76e501ef1f91b8e0bba6ea/tzfile.5#L143)

**Comment by hhugo** [comment]
This should be fixed.
