### ISSUE TITLE
Cannot open Core.Std within utop

### ISSUE THREAD

**Issue by chydenius** [janestreet/core#66]
In terminal, I can verify that I have installed core using OPAM:

:~/.opam/packages$ ls
base-bigarray  bitcoin      cryptokit      lwt         pa_test    variantslib
base-bytes     camlp4       custom_printf  ocamlbuild  pipebang   yojson
base-no-ppx    camomile     easy-format    ocamlfind   react      zed
base-threads   comparelib   enumerate      omake       sexplib
base-unix      **core**         fieldslib      ounit       type_conv
biniou         core_kernel  herelib        pa_bench    typerep
bin_prot       cppo         lambda-term    pa_ounit    utop

However, when I try to open Core.Std in utop, I get:

utop # open Core.Std;;
Error: Unbound module Core 

Am I doing something wrong? I have restarted utop and my terminal several times, and nothing helps.

**Comment by trefis** [comment]
You need to `#require core` before being able to open.
Also to list the installed packages one usually do `ocamlfind list`

**Comment by chydenius** [comment]
Thank you for the fast response! 

This seems to have done the trick:

utop # **#require "core";;**
─( 12:18:22 )─< command 6 >────────────────────────────{ counter: 0 }─
utop # **open Core.Std;;**
─( 12:19:51 )─< command 7 >────────────────────────────{ counter: 0 }─
