### ISSUE TITLE
Tuple2.mapn

### ISSUE THREAD

**Issue by esad** [janestreet/core#67]
Tuple2 provides `map1` and `map2`, which apply the provided function to the first or the second element. However there's no convenient way to map the same function to both elements, provided they're of same type. Batteries include `mapn` for this purpose, could we have something similar in Core?

**Comment by bmillwood** [comment]
(Side note: Tuple2.map2 is terribly-named, being in no way analogous to say Option.map2 or Or_error.map2)

**Comment by bcc32** [comment]
`Tuple2.map` is now available in the GitHub version of `core_kernel`.  It will appear in the next opam stable release.
