### ISSUE TITLE
Time module issue (or documentation issue, not sure).

### ISSUE THREAD

**Issue by onokognome** [janestreet/core#71]
The documentation for the Time module says:
**to_string_trimmed t Same as to_string, but removes trailing seconds and milliseconds if they are 0**

**to_sec_string t Same as to_string, but without milliseconds**

However, these appear to require a Zone.t argument - which 'to_string' does not.

Example:
**let now = Time.now()**
**print_string (((Time.to_sec_string now) Time.Zone.local)^"\n")** works
**print_string ((Time.to_sec_string now)^"\n")**  causes "This expression has type zone:Core.Time.Zone.t -> string but an expression was expected of type string"

**Comment by bmillwood** [comment]
I think the latest version of these doc comments refer to `to_string_abs` instead of `to_string`, which is correct.
