### ISSUE TITLE
No such package: sexplib.syntax

### ISSUE THREAD

**Issue by auxym** [janestreet/core#72]
I get the following error message when I try to use Core:

```
No such package: sexplib.syntax - required by `core.syntax'
```

Using `core.113.24.01`, `sexplib.113.24.00` and ocaml 4.02.3. See also this SO question: http://stackoverflow.com/questions/35506065/utop-error-no-such-package-sexplib-syntax-required-by-core-syntax. Note that in my case (and that of a commenter) , an update/upgrade did not resolve the issue.

**Comment by diml** [comment]
Ah, `core.syntax` hasn't been updated to point to the new camlp4 names. I'll do that for next release. Note that the core camlp4 syntax extensions are now deprecated. The replacement in the ppx world is `ppx_jane`

**Comment by diml** [comment]
I updated the RWO instructions. With core 113.24.02, trying to use `core.syntax` result in an error:

```
$ ocamlfind ocamlc -package core.syntax
ocamlfind: Error from package `core.syntax': core.syntax is deprecated, use ppx_jane instead
```
