### ISSUE TITLE
symbol not found: _mkostemp

### ISSUE THREAD

**Issue by yminsky** [janestreet/core#74]
The error is below. Notably, the same code works fine when build with base or core_kernel. This happens on any source file with the latest release.

    $ ocamlbuild play.byte -pkg core
    + /Users/yminsky/.opam/4.03.0/bin/ocamlc.opt -I /Users/yminsky/.opam/4.03.0/lib/base -I /Users/yminsky/.opam/4.03.0/lib/bin_prot -I /Users/yminsky/.opam/4.03.0/lib/core -I /Users/yminsky/.opam/4.03.0/lib/core_kernel -I /Users/yminsky/.opam/4.03.0/lib/fieldslib -I /Users/yminsky/.opam/4.03.0/lib/num -I /Users/yminsky/.opam/4.03.0/lib/ocaml -I /Users/yminsky/.opam/4.03.0/lib/ppx_assert -I /Users/yminsky/.opam/4.03.0/lib/ppx_bench -I /Users/yminsky/.opam/4.03.0/lib/ppx_expect -I /Users/yminsky/.opam/4.03.0/lib/ppx_hash -I /Users/yminsky/.opam/4.03.0/lib/ppx_inline_test -I /Users/yminsky/.opam/4.03.0/lib/sexplib -I /Users/yminsky/.opam/4.03.0/lib/typerep -I /Users/yminsky/.opam/4.03.0/lib/variantslib unix.cma bigarray.cma caml.cma base0.cma shadow_stdlib.cma base.cma fieldslib.cma sexplib.cma variantslib.cma bin_shape_lib.cma bin_prot.cma nums.cma ppx_assert_lib.cma ppx_bench_lib.cma ppx_hash_lib.cma inline_test_config.cma ppx_inline_test_lib.cma typerep_lib.cma core_kernel.cma expect_test_common.cma expect_test_config.cma expect_test_collector.cma sexplib_unix.cma core.cma play.cmo -o play.byte
    File "_none_", line 1:
    Error: Error on dynamically loaded library: /Users/yminsky/.opam/4.03.0/lib/stublibs/dllcore_stubs.so: dlopen(/Users/yminsky/.opam/4.03.0/lib/stublibs/dllcore_stubs.so, 138): Symbol not found: _mkostemp
      Referenced from: /Users/yminsky/.opam/4.03.0/lib/stublibs/dllcore_stubs.so
      Expected in: flat namespace
     in /Users/yminsky/.opam/4.03.0/lib/stublibs/dllcore_stubs.so
    Command exited with code 2.
    Hint: Recursive traversal of subdirectories was not enabled for this build,
      as the working directory does not look like an ocamlbuild project (no
      '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
      you should add the option "-r" or create an empty '_tags' file.

      To enable recursive traversal for some subdirectories only, you can use the
      following '_tags' file:

	  true: -traverse
	  <dir1> or <dir2>: traverse

    Compilation unsuccessful after building 3 targets (1 cached) in 00:00:00.

**Comment by diml** [comment]
indeed, there is no mkostemp on OSX. I added a fallback

**Comment by yminsky** [comment]
FWIW, I don't think the opam repo has been updated to pick this up yet; or, at least, doing an opam update/upgrade doesn't appear to solve the problem...

**Comment by diml** [comment]
should be fixed now

**Comment by yminsky** [comment]
Looks good. Thanks.
