### ISSUE TITLE
Compiled output not working in OSX

### ISSUE THREAD

**Issue by gjaldon** [janestreet/core#75]
Hi there! I'm new to Ocaml and was trying to run a simple program detailed here https://realworldocaml.org/v1/en/html/a-guided-tour.html#a-complete-program. The program compiles without error but running `./sum.native` immediately exits instead of waiting for user input. 

I'm using Ocaml 4.03.0 which was installed through opam. I also installed core through opam. I'm using OSX El Capitan. Could the problem be with my installation of Ocaml or is this an issue with Core have some incompatibility with OSX?

**Comment by hhugo** [comment]
I'm running OSX El Capitan (10.11.6)
The following works just fine:
```
$ ocamlc -version
4.03.0

$ cat test.ml 
open Core.Std

let rec read_and_accumulate accum =
  let line = In_channel.input_line In_channel.stdin in
  match line with
  | None -> accum
  | Some x -> read_and_accumulate (accum +. Float.of_string x)

let () =
  printf "Total: %F\n" (read_and_accumulate 0.

$ corebuild test.byte
Finished, 3 targets (0 cached) in 00:00:01.

$ ./test.byte 
1
2
3
4
5
Total: 15.
```

**Comment by gjaldon** [comment]
Reinstalling opam and ocaml fixes this for me. Thanks for checking it out @hhugo!
