### ISSUE TITLE
ocamlfind: Package `sexplib.syntax' not found

### ISSUE THREAD

**Issue by artemgru** [janestreet/core#81]
hi all!
My ocaml version is 4.0.4

```
ocamlfind list | grep core
core                (version: 113.33.02+4.03)
core.syntax         (version: [deprecated])
core.top            (version: 113.33.02+4.03)
core_kernel         (version: 113.33.01+4.03)
num.core            (version: [internal])
ppx_core            (version: 113.33.01+4.03)
```

So I am getting this error:
ocamlfind: Package `sexplib.syntax' not found

I saw that this problem is possible to earlier version of core library.But I have the latest one.
Could you help me to fix it?!
It very important for me!

**Comment by diml** [comment]
`sexplib.syntax` was the camlp4 extension that is no longer supported. It still exist in opam as `pa_sexp_conv`, however you are encouraged to switch to its ppx replacement: `ppx_sexp_conv`
