### ISSUE TITLE
Union_find has no `find`

### ISSUE THREAD

**Issue by smolkaj** [janestreet/core#83]
Currently, the module `Union_find` does not support a `find` operation
```
find : 'a -> 'a t
```

**Comment by yminsky** [comment]
Is find supposed to do something different than create, which has the same
signature? Can you give an example of what you want to do that you can't
with the current signature?

**Comment by smolkaj** [comment]
`create` does not respect equality on `'a` in the following sense:
```
let x = Union_find.create 0
let y = Union_find.create 0
Union_find.same_class x y;;
>> - : bool = false
```
It would be useful to have a `find` operation that does respect equality, so that
`x = y` always implies `find x = find y`.

I suppose it's easy to implement such a `find` function simply by maintaining a Hashtable `classes` that maps `'a`s to their respective classes, and then defining
```
let find x = Hashtbl.find_or_add classes x ~default:(fun () -> Union_find.create x)
```
--------------------------------------------------------------------------------------------------
Update: Sorry, I just realized that what's usually called `find` in the literature is the `get` operation:
```
Union_find.get : 'a t -> 'a
```
It has type `'a t -> 'a` rather than `'a -> 'a t`.
