### ISSUE TITLE
Can't opam pin add core

### ISSUE THREAD

**Issue by alinpopa** [janestreet/core#88]
When trying to pin down core to a specific version, I'm getting this:
```
opam pin add core v0.9.0
core is now path-pinned to v0.9.0

[core] v0.9.0 unavailable
core is now unpinned from path v0.9.0
```
Tried also with `v0.9.1`, and got the same issue.
Is there any known issue with this, or is it deliberately this way?

Thanks.

**Comment by diml** [comment]
What about:

```
opam pin add core.v0.9.0
```

?

**Comment by alinpopa** [comment]
Doesn't work for a different reason:
```
opam pin add core.v0.9.0
opam: No valid package description found at path core.v0.9.0.
      Please supply at least a package name (e.g. `opam pin add NAME PATH')
```

**Comment by diml** [comment]
TBH, this is an opam issue, there is nothing special in core that would cause this.

**Comment by alinpopa** [comment]
Yeah, sure, I get that, only that it works fine for some packages (like `jbuilder`), but it doesn't work for `core` (and also other libs like `variantslib`).

**Comment by diml** [comment]
Oh, I see. I guess it's because of the `v` prefix, opam thinks it's a path rather than a `NAME.VERSION` string

**Comment by igstan** [comment]
Be explicit about wanting to pin a version (as opposed to a path) by using the `--kind` option:

```
opam pin add --kind=version core v0.9.0
```

**Comment by alinpopa** [comment]
Thanks both, guys.
