### ISSUE TITLE
Core Map

### ISSUE THREAD

**Issue by reservoirman** [janestreet/core#89]
hello, So I'm using Jane Street's Core.std for certain things in my program but still want to use the standard OCaml Map. However when I call functions like mem, it is expecting the signature of the Core.std version. How do I get past this hurdle? Thank you!

open Core.Std
open Map

```
module PortTable = Map.Make(String)
let portTable = PortTable.empty 
let string_add = (Int64.to_string packet.dlDst) in 
PortTable.mem string_add portTable
```
This will not compile for me, as it's expecting Core.std's version of mem, not the standard one:

```
Error: This expression has type string but an expression was expected of type
     'a PortTable.t = (string, 'a, PortTable.Key.comparator_witness) t
```
I just want to use the standard one. Or otherwise get these simple Map operations to work!  If anyone could help that would be much appreciated.

**Comment by yminsky** [comment]
You can use the Caml module to access the stdlib. So, Caml.Map should give you the standard OCaml map module.
