### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by brendanlong** [janestreet/core#91]
I'm not sure where the right place to report this is, but the documentation for several Jane Street modules seems to be broken:

https://ocaml.janestreet.com/ocaml-core/latest/doc/core/Std/String.mod/

Click basically any link here: https://ocaml.janestreet.com/ocaml-core/latest/doc/core/

Did the documentation move?

**Comment by trefis** [comment]
I agree that the first link you give points to nothing.
I don't know how you arrived on that link though. Clicking on the second link, everything in there seems to be linked properly. (and also ugly, but that's another issue)

**Comment by brendanlong** [comment]
Ohh this seems to be a caching issue. shift + refresh on that second page gets a completely different page. You might have a reverse proxy holding onto the old pages too long (or maybe my browser is just holding onto it too long)? Anyway, works for me now.
