### ISSUE TITLE
Add link to current API docs

### ISSUE THREAD

**Issue by mars0i** [janestreet/core#93]
Hi,

I suggest putting a link to the current API docs in the main README.md in this repo.

Searching with Google for the API docs for whatever is the current public release of Core (0.9.1 at the moment, but that doesn't matter) is difficult.  When searching for "ocaml core" or "ocaml jane street core", many of the top hits are not the latest API docs, and even the one that appears to be correct, https://ocaml.janestreet.com/ocaml-core/latest/doc/, is labeled "Jane Street packages API documentation - v0.9 - OCaml", which makes it unclear whether it's current.  This page https://janestreet.github.io does have link to the same API top level, but the page is labeled "Open Source @ Jane Street", which makes it seem as if there are other better links.  In fact one of the links that appears best is the one for this github repo, which is labeled "GitHub - janestreet/core: Jane Street Capital's standard library overlay".  Sounds perfect!  But you can't get to the API docs from there.  The git repo page is also what the OPAM page for Core points to, which also suggests that documentation links would be found there.  

(Thanks very much for Core, too.)

**Comment by lpw25** [comment]
(Sorry for the slow reply)

I think this is a good idea in principle, but we're not particularly happy with Core's documentation on that page yet. We've put some effort into making Base and Core_kernel's documentation usable, but have not got as far as sorting out Core yet -- and we think it will need a little more work on the odoc tool that generates it.

So I'm going to look into adding links in the readme's for Base and Core_kernel, but leave Core alone for now and come back to it when we're happier with the docs. I'll leave this issue open until we get to that point.

**Comment by mars0i** [comment]
OK--thanks.  I understand.  fwiw, I think the github README for Base is also a little unclear, without online API docs.  If the functionality is exactly like some part of the OCaml distribution apart from exceptions that the README notes, then it would be helpful to have a link to the relevant parts of the distribution, maybe.  Right now there's really no documentation at all for Base, that I can find, except for the README (or what I make with odoc, etc.!).

Maybe part of the problem concerns the names of the libraries?  Search engines end up being the front end of any online documentation, and "Base" and "Core" confuse them.  Compare ""ocaml batteries", which is easy to search.  Any thought of renaming the libraries?  Maybe "JSBase", "JSCore", or something like that?  Or less mundane, maybe: "StreetSmart", "JaneBase", etc.  Thanks.

**Comment by lpw25** [comment]
I changed my mind and decided to add the link from Core's readme now. Even though the documentation is rubbish, the readme is rubbish too so it probably doesn't make things any worse, and it saves me from trying to remember to update the readme later once the documentation is fixed.

So the readmes of Base, Core_kernel and Core should all be updated to include links to the documentation when they are next released.

I can't see use renaming any of the libraries. Google brings you to the right place for "ocaml base" and "ocaml core". The documentation doesn't appear in the listing for base, but that has more to do with there being no links to it from anywhere than the name. In the not to distant future `opam.ocaml.org` will have all the docs for everything in an easy to find location, which should make things easier.

**Comment by mars0i** [comment]
Thanks!  (laughing ... about the rubbish part) .  

You're right about Google and Base.  I don't know how I was searching.  Obviously not the obvious way. :-)   "ocaml core" is actually still problematic, imho.  The top link I get is an old set of docs, I think, v111.17.  The third link I get is Core.Std.List from 109.22.  The second link looks right if you notice that the URL contains "/latest/", and it takes you straight to the index.  The fourth link comes back to this github repo.  The fifth link is the one I've trusted, because it looks official, and has a link to the "/latest/" index.  So the second and fifth links are right, but figuring that out is confusing.  However, my guess is that Google will eventually figure out the correct link to put at the top when the doc system is touched up.  I understand not wanting to change the names.  Was just a thought.  Part of the OCaml distribution standard lib is sometimes referred to as "core" or "base"--I forget which.  Anyway, thanks for working on all of this.
