### ISSUE TITLE
Multiple definitions of unix_initgroups & unix_nice

### ISSUE THREAD

**Issue by alfa07** [janestreet/core#97]
While trying to link core I get the following link error:

OCaml link
stderr: ocaml-core/lib/core/libcore_stubs.a(unix_stubs.o): multiple definition of 'unix_initgroups'
bin/gold/ld: build/ocaml/lib/ocaml/libunix.a(initgroups.o): previous definition here
bin/gold/ld: error: build/ocaml-core/lib/core/libcore_stubs.a(unix_stubs.o): multiple definition of 'unix_nice'
bin/gold/ld: build/ocaml/lib/ocaml/libunix.a(nice.o): previous definition here
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking

If I understand dependencies correctly then the chain looks like it:
core -> spawn -> unix
and this gives duplicate symbol:

https://github.com/janestreet/core/blob/705b226581fe04a2608718ae581498a3e688c433/src/unix_stubs.c#L1652

https://github.com/ocaml/ocaml/blob/trunk/otherlibs/unix/nice.c#L23

That is custom build in buck (but all the libraries were built first in jbuilder)

I guess I am missing something, any tips?

EDIT:

Managed to build by renaming unix_initgroups to core_unix_initgroups and unix_nice to core_unix_nice. I am still puzzled how build should succeed with name conflicts!

**Comment by mroch** [comment]
this looks like it was fixed in 0.13
